Random Sampling
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Juhyeon/Desktop/repository/Proxy-Anchor-CVPR2020/code/train.py", line 234, in <module>
    criterion = losses.ContrastivePCALoss().cuda()
  File "C:\Users\Juhyeon\Desktop\repository\Proxy-Anchor-CVPR2020\code\losses.py", line 210, in __init__
    self.loss_func = ContrastivePCALoss(neg_margin=self.margin)
  File "C:\Users\Juhyeon\Desktop\repository\Proxy-Anchor-CVPR2020\code\losses.py", line 210, in __init__
    self.loss_func = ContrastivePCALoss(neg_margin=self.margin)
  File "C:\Users\Juhyeon\Desktop\repository\Proxy-Anchor-CVPR2020\code\losses.py", line 210, in __init__
    self.loss_func = ContrastivePCALoss(neg_margin=self.margin)
  [Previous line repeated 744 more times]
  File "C:\Users\Juhyeon\Desktop\repository\Proxy-Anchor-CVPR2020\code\losses.py", line 208, in __init__
    super(ContrastivePCALoss, self).__init__()
  File "C:\Users\Juhyeon\anaconda3\envs\torch17\lib\site-packages\torch\nn\modules\module.py", line 229, in __init__
    self.training = True
RecursionError: maximum recursion depth exceeded while calling a Python object
